import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import ClientProvider from "./ClientProvider";
import "./globals.css";
import "@/assets/scss/main.css";
import "@/assets/scss/main.scss";
import styles from "@/assets/css/base.module.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "iwebwiser",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} noSeect ${geistMono.variable} ${poppins.className}`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
